language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: BYw8cLEfQW4FuzyFUEXSzYVjh64M08tXSdbY3GbTrWJwxRSlpiBJSw5nVJ0nX07gitID/52CNueIR0n/8ApxP/fue1VBMoMQdvkZCWAkd6P452+pfR4C0aU0VxHscgkKRcN44qF8Jr98lPnEcBPtBpKMzcvDAc8W6OC6gRF0IuKOs4Gb3JrpLo7N7SODolD90Tidpn5via9a9WEq83Dup+BQunbz+mTYs3Z0VIV6nyvsl0NOEEWxcWzteyVd/E0kKiAxOIy3urDr2zWQ9SSk0Bo6OZXv8c0MxuqGEUdVk9ThpVfCXazpZ8jERsZq0LFkSyuns62ffm5YYb7iXZfvs9S8eMNvRzOZFwDXrrzss6of3eCpDXdrQJO6bBqm/VzXTHM7jLESkILX2u9p5ywPulD3UpIxAgcSrHKNpbSRodiEtru5C4mIyGULOlfsn/RPob+n0zsahwME3S0/6PFpTmDjdCaJ9r/ULw0+WG2deOBfUfkGo0wVrwdhU2MucC5Dy4P1tK36Ypvo7xsqte9Zdd2NyCV+7sTswLUIlvlMLo2/GGU3TXkTb/8UWoHzfWpHIECBINkw6bpO3twhBGL8hBBZI58NTPNAmferN3MN0cTvxVzUgA+kOWUL1rbfHL8rzWKl+IBtlW9S9Or2IYhaDPcmtsZAGWBp+O3i5Uqnncw=
  app: ist-uex-test
